server:
  port: 8090

spring:
  application:
    name: msvc-user
  security:
    user:
      name: admin
      password: admin
      roles: ADMIN
  data:
    mongodb:
      host: localhost
      port: 27017
      database: userDb
  config:
    import: optional:configserver:http://localhost:8888
    
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka