server:
  port: 8080

spring:
  application:
    name: msvc-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user
          uri: lb://msvc-user
          predicates:
            - Path=/api/user/**
        - id: news
          uri: lb://msvc-news
          predicates:
            - Path=/api/news/**