server:
  port: 8080

spring:
  application:
    name: msvc-gateway
  config:
    import: optional:configserver:http://localhost:8888

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # Habilita el descubrimiento automático de servicios
      routes:
        - id: msvc-user-route
          uri: lb://MSVC-USER  # Usando el nombre del servicio registrado en Eureka
          predicates:
            - Path=/api/user/**
            - Path=/msvc-user/swagger-ui/**
          filters:
            - StripPrefix=1
        - id: msvc-news-route
          uri: lb://MSVC-NEWS  # Usando el nombre del servicio registrado en Eureka
          predicates:
            - Path=/api/news/**, /msvc-news/v3/api-docs/**
        - id: msvc-web-route
          uri: lb://MSVC-WEB  # Usando el nombre del servicio registrado en Eureka
          predicates:
            - Path=/api/web/**, /css/**, /images/**  # Cambia el path según lo que necesites
          


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/  # Dirección de tu servidor Eureka
