server:
  port: 8080

spring:
  application:
    name: msvc-web
  security:
    user:
      name: admin
      password: admin
      roles: ADMIN
  config:
    import: optional:configserver:http://localhost:8888
    
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka