server:
  port: 9090


spring:
  security:
    user:
      name: admin
      password: admin
      roles: ADMIN
  application:
    name: msvc-news
  data:
    mongodb:
      uri: mongodb://localhost:27017/newsDb
  config:
    import: optional:configserver:http://localhost:8888
    
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka