server:
  port: 9090


spring:
  security:
    user:
      name: admin
      password: admin
      roles: ADMIN
  application:
    name: msvc-news
  data:
    mongodb:
      uri: mongodb://localhost:27017/newsDb
  codec:
    max-in-memory-size: 2000KB
  config:
    import: optional:configserver:http://localhost:8888
    
    
openapi:
  service:
    title: msvc news doc
    version: 1.0.0
    url: http://localhost:8080 #api gateway url
springdoc:
  api-docs:
    path: /mscv-news/v3/api-docs
  swagger-ui:
    path: /msvc-news/swagger-ui.html
    
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka